2021-11-18 09:39:53,070 -Loc multi_threaded_logger.py -Pid 12207 -root -ERROR - test error log1
2021-11-18 09:40:00,253 -Loc multi_threaded_logger.py -Pid 12206 -root -ERROR - test error log0
2021-11-18 09:40:00,277 -Loc multi_threaded_logger.py -Pid 12207 -root -ERROR - test error log2
2021-11-18 09:40:02,290 -Loc multi_threaded_logger.py -Pid 12206 -root -ERROR - test error log3
2021-11-18 09:40:02,308 -Loc multi_threaded_logger.py -Pid 12207 -root -ERROR - test error log4
2021-11-18 09:40:04,320 -Loc multi_threaded_logger.py -Pid 12206 -root -ERROR - test error log5
2021-11-18 09:40:04,338 -Loc multi_threaded_logger.py -Pid 12207 -root -ERROR - test error log6
2021-11-18 09:40:06,353 -Loc multi_threaded_logger.py -Pid 12206 -root -ERROR - test error log7
2021-11-18 09:40:06,369 -Loc multi_threaded_logger.py -Pid 12207 -root -ERROR - test error log8
2021-11-18 09:40:08,384 -Loc multi_threaded_logger.py -Pid 12206 -root -ERROR - test error log9
2021-11-18 09:46:38,808 -Loc multi_threaded_logger.py -Pid 12305 -root -ERROR - test error log0
2021-11-18 09:46:38,808 -Loc multi_threaded_logger.py -Pid 12306 -root -ERROR - test error log1
2021-11-18 09:46:40,819 -Loc multi_threaded_logger.py -Pid 12305 -root -ERROR - test error log2
2021-11-18 09:46:40,819 -Loc multi_threaded_logger.py -Pid 12306 -root -ERROR - test error log3
2021-11-18 09:46:42,829 -Loc multi_threaded_logger.py -Pid 12305 -root -ERROR - test error log4
2021-11-18 09:46:42,829 -Loc multi_threaded_logger.py -Pid 12306 -root -ERROR - test error log5
2021-11-18 09:46:44,842 -Loc multi_threaded_logger.py -Pid 12305 -root -ERROR - test error log6
2021-11-18 09:46:44,842 -Loc multi_threaded_logger.py -Pid 12306 -root -ERROR - test error log7
2021-11-18 09:46:46,856 -Loc multi_threaded_logger.py -Pid 12306 -root -ERROR - test error log9
2021-11-18 09:46:46,856 -Loc multi_threaded_logger.py -Pid 12305 -root -ERROR - test error log8
2021-11-18 09:49:42,118 -Loc multi_threaded_logger.py -Pid 12361 -root -ERROR - test error log0
2021-11-18 09:49:42,122 -Loc multi_threaded_logger.py -Pid 12362 -root -ERROR - test error log1
2021-11-18 09:49:44,134 -Loc multi_threaded_logger.py -Pid 12361 -root -ERROR - test error log2
2021-11-18 09:49:44,135 -Loc multi_threaded_logger.py -Pid 12362 -root -ERROR - test error log3
2021-11-18 09:49:46,148 -Loc multi_threaded_logger.py -Pid 12361 -root -ERROR - test error log4
2021-11-18 09:49:46,148 -Loc multi_threaded_logger.py -Pid 12362 -root -ERROR - test error log5
2021-11-18 09:49:48,160 -Loc multi_threaded_logger.py -Pid 12362 -root -ERROR - test error log7
2021-11-18 09:49:48,160 -Loc multi_threaded_logger.py -Pid 12361 -root -ERROR - test error log6
2021-11-18 09:49:50,172 -Loc multi_threaded_logger.py -Pid 12361 -root -ERROR - test error log9
2021-11-18 09:49:50,172 -Loc multi_threaded_logger.py -Pid 12362 -root -ERROR - test error log8
2021-11-18 09:50:50,210 -Loc multi_threaded_logger.py -Pid 12383 -root -ERROR - test error log0
2021-11-18 09:50:50,211 -Loc multi_threaded_logger.py -Pid 12384 -root -ERROR - test error log1
2021-11-18 09:50:52,224 -Loc multi_threaded_logger.py -Pid 12384 -root -ERROR - test error log3
2021-11-18 09:50:52,224 -Loc multi_threaded_logger.py -Pid 12383 -root -ERROR - test error log2
2021-11-18 09:50:54,237 -Loc multi_threaded_logger.py -Pid 12383 -root -ERROR - test error log5
2021-11-18 09:50:54,237 -Loc multi_threaded_logger.py -Pid 12384 -root -ERROR - test error log4
2021-11-18 09:50:56,252 -Loc multi_threaded_logger.py -Pid 12383 -root -ERROR - test error log6
2021-11-18 09:50:56,253 -Loc multi_threaded_logger.py -Pid 12384 -root -ERROR - test error log7
2021-11-18 09:50:58,266 -Loc multi_threaded_logger.py -Pid 12384 -root -ERROR - test error log9
2021-11-18 09:50:58,266 -Loc multi_threaded_logger.py -Pid 12383 -root -ERROR - test error log8
2021-11-18 09:52:25,622 -Loc multi_threaded_logger.py -Pid 12419 -root -ERROR - test error log0
2021-11-18 09:52:25,622 -Loc multi_threaded_logger.py -Pid 12420 -root -ERROR - test error log1
2021-11-18 09:52:27,634 -Loc multi_threaded_logger.py -Pid 12420 -root -ERROR - test error log3
2021-11-18 09:52:27,634 -Loc multi_threaded_logger.py -Pid 12419 -root -ERROR - test error log2
2021-11-18 09:52:29,648 -Loc multi_threaded_logger.py -Pid 12420 -root -ERROR - test error log4
2021-11-18 09:52:29,648 -Loc multi_threaded_logger.py -Pid 12419 -root -ERROR - test error log5
2021-11-18 09:52:31,663 -Loc multi_threaded_logger.py -Pid 12419 -root -ERROR - test error log7
2021-11-18 09:52:31,663 -Loc multi_threaded_logger.py -Pid 12420 -root -ERROR - test error log6
2021-11-18 09:52:33,676 -Loc multi_threaded_logger.py -Pid 12420 -root -ERROR - test error log9
2021-11-18 09:52:33,676 -Loc multi_threaded_logger.py -Pid 12419 -root -ERROR - test error log8
2021-11-18 09:58:35,551 -Loc multi_threaded_logger.py -Pid 12522 -root -ERROR - test error log1
2021-11-18 09:58:35,551 -Loc multi_threaded_logger.py -Pid 12521 -root -ERROR - test error log0
2021-11-18 09:58:37,566 -Loc multi_threaded_logger.py -Pid 12521 -root -ERROR - test error log3
2021-11-18 09:58:37,566 -Loc multi_threaded_logger.py -Pid 12522 -root -ERROR - test error log2
2021-11-18 09:58:39,581 -Loc multi_threaded_logger.py -Pid 12521 -root -ERROR - test error log4
2021-11-18 09:58:39,581 -Loc multi_threaded_logger.py -Pid 12522 -root -ERROR - test error log5
2021-11-18 09:58:41,597 -Loc multi_threaded_logger.py -Pid 12521 -root -ERROR - test error log6
2021-11-18 09:58:41,597 -Loc multi_threaded_logger.py -Pid 12522 -root -ERROR - test error log7
2021-11-18 09:58:43,610 -Loc multi_threaded_logger.py -Pid 12522 -root -ERROR - test error log9
2021-11-18 09:58:43,610 -Loc multi_threaded_logger.py -Pid 12521 -root -ERROR - test error log8
2021-11-18 09:59:52,195 -Loc multi_threaded_logger.py -Pid 12547 -root -ERROR - test error log1
2021-11-18 09:59:52,195 -Loc multi_threaded_logger.py -Pid 12546 -root -ERROR - test error log0
2021-11-18 09:59:54,206 -Loc multi_threaded_logger.py -Pid 12546 -root -ERROR - test error log3
2021-11-18 09:59:54,206 -Loc multi_threaded_logger.py -Pid 12547 -root -ERROR - test error log2
2021-11-18 09:59:56,220 -Loc multi_threaded_logger.py -Pid 12546 -root -ERROR - test error log4
2021-11-18 09:59:56,221 -Loc multi_threaded_logger.py -Pid 12547 -root -ERROR - test error log5
2021-11-18 09:59:58,234 -Loc multi_threaded_logger.py -Pid 12546 -root -ERROR - test error log6
2021-11-18 09:59:58,236 -Loc multi_threaded_logger.py -Pid 12547 -root -ERROR - test error log7
2021-11-18 10:00:00,244 -Loc multi_threaded_logger.py -Pid 12547 -root -ERROR - test error log9
2021-11-18 10:00:00,244 -Loc multi_threaded_logger.py -Pid 12546 -root -ERROR - test error log8
2021-11-18 10:13:15,073 -Loc multi_threaded_logger.py -Pid 12753 -root -ERROR - test error log0
2021-11-18 10:13:15,073 -Loc multi_threaded_logger.py -Pid 12754 -root -ERROR - test error log1
2021-11-18 10:13:17,086 -Loc multi_threaded_logger.py -Pid 12754 -root -ERROR - test error log3
2021-11-18 10:13:17,086 -Loc multi_threaded_logger.py -Pid 12753 -root -ERROR - test error log2
2021-11-18 10:13:19,100 -Loc multi_threaded_logger.py -Pid 12753 -root -ERROR - test error log5
2021-11-18 10:13:19,100 -Loc multi_threaded_logger.py -Pid 12754 -root -ERROR - test error log4
2021-11-18 10:13:21,112 -Loc multi_threaded_logger.py -Pid 12753 -root -ERROR - test error log6
2021-11-18 10:13:21,112 -Loc multi_threaded_logger.py -Pid 12754 -root -ERROR - test error log7
2021-11-18 10:13:23,127 -Loc multi_threaded_logger.py -Pid 12753 -root -ERROR - test error log8
2021-11-18 10:13:23,127 -Loc multi_threaded_logger.py -Pid 12754 -root -ERROR - test error log9
2021-11-18 10:18:37,672 -Loc multi_threaded_logger.py -Pid 12837 -root -ERROR - test error log1
2021-11-18 10:18:37,673 -Loc multi_threaded_logger.py -Pid 12836 -root -ERROR - test error log0
2021-11-18 10:18:39,687 -Loc multi_threaded_logger.py -Pid 12836 -root -ERROR - test error log3
2021-11-18 10:18:39,688 -Loc multi_threaded_logger.py -Pid 12837 -root -ERROR - test error log2
2021-11-18 10:18:41,701 -Loc multi_threaded_logger.py -Pid 12837 -root -ERROR - test error log5
2021-11-18 10:18:41,701 -Loc multi_threaded_logger.py -Pid 12836 -root -ERROR - test error log4
2021-11-18 10:18:43,714 -Loc multi_threaded_logger.py -Pid 12837 -root -ERROR - test error log6
2021-11-18 10:18:43,715 -Loc multi_threaded_logger.py -Pid 12836 -root -ERROR - test error log7
2021-11-18 10:18:45,728 -Loc multi_threaded_logger.py -Pid 12837 -root -ERROR - test error log8
2021-11-18 10:18:45,728 -Loc multi_threaded_logger.py -Pid 12836 -root -ERROR - test error log9
